DROP FUNCTION IF EXISTS time_subtype_diff CASCADE;
DROP INDEX IF EXISTS available_idx CASCADE;
DROP TABLE IF EXISTS availability_rules CASCADE;
DROP TABLE IF EXISTS available_time CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS event_templates CASCADE;

    CREATE FUNCTION time_subtype_diff(x time, y time) RETURNS float8 AS
    'SELECT EXTRACT(EPOCH FROM (x - y))' LANGUAGE sql STRICT IMMUTABLE;

    CREATE TYPE timerange AS RANGE (
    subtype = time,
    subtype_diff = time_subtype_diff
    );

     CREATE TABLE IF NOT EXISTS availability_rules (
     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     weekday                  INT NOT NULL,
     range                    TIMERANGE NOT NULL
     );

     CREATE INDEX IF NOT EXISTS availability_rules_idx ON availability_rules USING gist (range);

     CREATE TABLE IF NOT EXISTS event_templates (
     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     duration_minutes         INT NOT NULL CHECK (duration_minutes > 0),
     start_time               TIMESTAMP NOT NULL,
     end_time                 TIMESTAMP NOT NULL,
     buffer_before_minutes    INT DEFAULT 0 CHECK (buffer_before_minutes >= 0),
     buffer_after_minutes     INT DEFAULT 0 CHECK (buffer_after_minutes >= 0)
     );

     CREATE TABLE IF NOT EXISTS available_time (
     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     range                    TSRANGE NOT NULL
     );

     CREATE INDEX IF NOT EXISTS available_idx ON available_time USING gist (range);

     CREATE TABLE IF NOT EXISTS bookings (
     id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     event_template_id        BIGINT NOT NULL REFERENCES event_templates(id) ON DELETE CASCADE,
     start_time               TIMESTAMP NOT NULL,
     end_time                 TIMESTAMP NOT NULL
     );

